name: build

on:
    push:
      branch:
        - master
        - develop
    pull_request:
      branches:
        - master
        - develop
# need hypothesis

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        #python-version: [3.6, 3.7, 3.8]
        python-version: [3.6, 3.7]
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest hypothesis
      - name: Setenv
        run: echo "::set-env name=PYTHONPATH::$GITHUB_WORKSPACE:$PYTHONPATH"
      - name: Test with pytest
        run: |
          pytest
    